export const images = {
  calender: require('../../assets/Images/calendar.png'),
  ArrowDown: require('../../assets/Images/arrowDown.png'),
  close: require('../../assets/Images/close.png'),
  noData: require('../../assets/Images/file.png'),
  rightArrow: require('../../assets/Images/rightarrow.png'),
  manhair: require('../../assets/Images/manhair.png'),
  support: require('../../assets/Images/support.png'),
  offer: require('../../assets/Images/offer.png'),
  info: require('../../assets/Images/info.png'),
  phone: require('../../assets/Images/phone.png'),
  discount: require('../../assets/Images/discount.png'),
  money: require('../../assets/Images/money.png'),
  promo: require('../../assets/Images/promo.png'),
  compose: require('../../assets/Images/compose.png'),
  calculator: require('../../assets/Images/calculator.png'),
  cross2: require('../../assets/Images/cross2.png'),
  userprofile: require('../../assets/Images/userprofile.png'),
  logo: require('../../assets/Images/logo.png'),
  call: require('../../assets/Images/call.png'),
  calendar: require('../../assets/Images/calendar.png'),
  mark: require('../../assets/Images/mark.png'),
  nodata: require('../../assets/Images/nodata.png'),
  search: require('../../assets/Images/search.png'),
  profile: require('../../assets/Images/profile.png'),
};
